### ISSUE TITLE
side by side diffs needs to truncate long lines

### ISSUE THREAD

**Issue by mcr** [ietf-tools/iddiff#30]
Consider the diff given by:

https://www.ietf.org/rfcdiff?url1=https://tools.ietf.org/id/draft-ietf-rats-eat.txt&url2=https://ietf-rats-wg.github.io/eat/draft-ietf-rats-eat.txt

The page loads and then somewhere at the bottom, some really long line occurs, and the left-side occupies the entire browser.
After some CTRL+- and scrolling, this occurs due to some unwrapped text down in appendix A.1.7.  
Can we use some CSS to truncate overlong lines like this?

**Comment by kesara** [comment]
I think this was due to an escaping issue, which is now fixed.
